//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceTest.DataWorker
{
    using System;
    using System.Collections.Generic;
    
    public partial class data
    {
        public int Id { get; set; }
        public string TypeEvent { get; set; }
        public string email { get; set; }
        public string sms { get; set; }
    }
}
