//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceTest.DataWorker
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Migrations;

    public partial class MyDataBaseEntities : DbContext
    {

        public MyDataBaseEntities()
            : base("name=MyDataBaseEntities")
        {
            Database.SetInitializer<MyDataBaseEntities>(new SampleInitial());
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<data> data { get; set; }
    }
    public class SampleInitial : DropCreateDatabaseAlways<MyDataBaseEntities>
    {
        protected override void Seed(MyDataBaseEntities context)
        {
            List<data> myData = new List<data>();
            Random rd = new Random();
            for (int i = 0; i < 10; i++)
            {
                data temp = new data();
                string te= ((TypeEvent)rd.Next(1, 3)).ToString("G");
                temp.TypeEvent = te;
                temp.email = @"halk0812@yandex.ru";
                temp.sms = "+79374023852";
                myData.Add(temp);
            }
            context.data.AddRange(myData);
            context.SaveChanges();
           // base.Seed(context);
        }
    }
   
}
